import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/styles.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next RPG Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-screen h-screen relative ${inter.className}`} >{children}</body>
    </html>
  );
}
