import type { Metadata } from "next";
import { Inter, Pirata_One } from "next/font/google";
import '@/public/styles.css';
const inter = Inter({ subsets: ["latin"] });
const pirataOne = Pirata_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next RPG Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-dvw h-dvh m-0 relative ${pirataOne.className}`} >{children}</body>
    </html>
  );
}
