import type { Metadata } from "next";
import { Inter, Pirata_One, Grenze_Gotisch } from "next/font/google";
import "@/public/styles.css";
const inter = Inter({ subsets: ["latin"] });
const grenze_gotish = Grenze_Gotisch({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next RPG Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-dvw h-dvh m-0 relative ${grenze_gotish.className}`} >{children}</body>
    </html>
  );
}
